Formatted text
dylhack/matrix-plugin pull request #13
Opened 2021-01-23 11:40 UTC by amalon

This adds support for formatted matrix messages, as implemented in https://github.com/dylhack/matrix-appservice-minecraft/pull/31

- First we pass the JSON through to plugins, with some prettification done when prefixing sender name
- Then a short commit to relocate a helper
- Then we have a new IntermediateJSON class for handling the formatting in a common way, using the Adventure text API
- Finally support in polo-bukkit for using IntermediateJSON class and sending the formatted text to players and the console using Adventure's BukkitAudiences.

2021-01-23 15:32 UTC, dylhack requested changes
Just one nitpick

2021-01-23 15:32 UTC, dylhack commented on polo-common/src/main/java/dev/dhdf/polo/types/IntermediateJSON.java
> +    private Component toComponent(/* inputs */
nitpick: Could you split this function up to smaller functions?

2021-01-26 13:57 UTC, amalon commented on polo-common/src/main/java/dev/dhdf/polo/types/IntermediateJSON.java
> +    private Component toComponent(/* inputs */
How's the new version look?

2021-01-26 13:58 UTC, amalon commented
New version, split toComponent(), fixed minor bug with nested obfuscation, and made bukkit mention handling line a bit shorter

2021-01-26 14:48 UTC, dylhack commented on polo-common/src/main/java/dev/dhdf/polo/types/IntermediateJSON.java
> +    private Component toComponent(/* inputs */
I'll check it out now.

2021-01-26 14:50 UTC, dylhack approved these changes

2021-02-09 06:08 UTC, aimiebell commented on polo-common/src/main/java/dev/dhdf/polo/types/IntermediateJSON.java
> +        if (href != "") {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [ES: Comparison of String objects using == or != (ES_COMPARING_STRINGS_WITH_EQ)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#es-comparison-of-string-objects-using-or-es-comparing-strings-with-eq).
This code compares java.lang.String objects for reference equality using the == or != operators. Unless both strings are either constants in a source file, or have been interned using the String.intern() method, the same string value may be represented by two different String objects. Consider using the equals(Object) method instead.

2021-02-09 09:00 UTC, amalon commented on polo-common/src/main/java/dev/dhdf/polo/types/IntermediateJSON.java
> +        if (href != "") {
Good spot, I'll fix that

2021-02-09 17:04 UTC, merged